"""
MedVision ConvNeXt-Tiny Standalone Inference CLI
Chest X-Ray 3-Class Disease Prediction (NORMAL, PNEUMONIA, TUBERCULOSIS)

Usage:
  python predict_convnext_tiny.py
  python predict_convnext_tiny.py --checkpoint "path/to/best_model.pth"
  python predict_convnext_tiny.py --image "path/to/xray.png"
"""

import os
import sys
import argparse
from PIL import Image
import torch
from torchvision import transforms

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

from src.model import build_convnext_tiny
from src.dataset import SafeRGB, CLASS_NAMES, IMAGENET_MEAN, IMAGENET_STD

DEFAULT_CHECKPOINT = os.path.join(CURRENT_DIR, "models", "chest_xray_convnext_tiny", "best_model.pth")


def get_inference_transform() -> transforms.Compose:
    return transforms.Compose([
        SafeRGB(),
        transforms.Resize((224, 224), interpolation=transforms.InterpolationMode.BILINEAR),
        transforms.ToTensor(),
        transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ])


def load_convnext_tiny_model(checkpoint_path: str, device: torch.device):
    """
    Loads ConvNeXt-Tiny model and checkpoint weights onto specified device.
    Fails immediately if checkpoint does not exist.
    """
    if not os.path.isfile(checkpoint_path):
        print(f"\n[ERROR] Checkpoint not found at: {checkpoint_path}")
        print(f"Please verify that the trained checkpoint exists before running inference.")
        sys.exit(1)

    model = build_convnext_tiny(num_classes=len(CLASS_NAMES), pretrained=False)
    ckpt = torch.load(checkpoint_path, map_location=device)
    if isinstance(ckpt, dict) and "model_state_dict" in ckpt:
        model.load_state_dict(ckpt["model_state_dict"])
        epoch_val = ckpt.get("epoch", "N/A")
    elif isinstance(ckpt, dict) and "state_dict" in ckpt:
        model.load_state_dict(ckpt["state_dict"])
        epoch_val = ckpt.get("epoch", "N/A")
    else:
        model.load_state_dict(ckpt)
        epoch_val = "N/A"

    ckpt_status = f"Loaded weights from {os.path.basename(checkpoint_path)} (Epoch {epoch_val})"
    model = model.to(device)
    model.eval()
    return model, ckpt_status


def predict_single_image(
    image_path: str,
    model: torch.nn.Module,
    device: torch.device,
    transform: transforms.Compose,
    ckpt_status: str,
):
    """
    Executes inference for a single chest X-ray image using preloaded model.
    """
    if not os.path.isfile(image_path):
        print(f"\nERROR: Image not found:\n{image_path}\n")
        return None

    try:
        with Image.open(image_path) as img:
            tensor = transform(img).unsqueeze(0).to(device)
    except Exception as e:
        print(f"\nERROR: Failed to open image {image_path}: {e}\n")
        return None

    with torch.no_grad():
        with torch.amp.autocast(device_type="cuda" if device.type == "cuda" else "cpu", dtype=torch.float16):
            logits = model(tensor)
            probs = torch.softmax(logits, dim=1).squeeze(0).cpu().tolist()

    pred_idx = int(torch.argmax(logits, dim=1).item())
    pred_class = CLASS_NAMES[pred_idx]
    top_confidence = probs[pred_idx]

    print("\n" + "=" * 65)
    print("MEDVISION CONVNEXT-TINY: CHEST X-RAY INFERENCE RESULT")
    print("=" * 65)
    print(f"Image File:        {image_path}")
    print(f"Filename:          {os.path.basename(image_path)}")
    print(f"Status:            {ckpt_status}")
    print(f"Predicted Class:   {pred_class}")
    print(f"Top Confidence:    {top_confidence * 100:.2f}%")
    print("-" * 65)
    print("Class Probabilities:")
    for cls_name, p in zip(CLASS_NAMES, probs):
        bar = "=" * int(p * 30)
        print(f"  {cls_name:<14}: {p * 100:6.2f}%  | {bar}")
    print("=" * 65)
    print("CLINICAL NOTICE:")
    print("Softmax confidence is model confidence and is not clinical certainty.")
    print("This prediction is generated by an experimental AI model for research")
    print("purposes only. It is NOT validated for primary medical or clinical diagnosis.")
    print("=" * 65 + "\n")

    return {
        "file_path": image_path,
        "filename": os.path.basename(image_path),
        "predicted_class": pred_class,
        "predicted_index": pred_idx,
        "top_confidence": top_confidence,
        "probabilities": {cls_name: p for cls_name, p in zip(CLASS_NAMES, probs)},
    }


def main():
    parser = argparse.ArgumentParser(description="ConvNeXt-Tiny Chest X-ray Inference CLI")
    parser.add_argument("--image", type=str, default=None, help="Path to input chest X-ray image (.png/.jpg)")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=DEFAULT_CHECKPOINT,
        help="Path to trained checkpoint (.pth)",
    )
    args = parser.parse_args()

    checkpoint_path = args.checkpoint
    if not os.path.isfile(checkpoint_path):
        print(f"\n[ERROR] Checkpoint not found at: {checkpoint_path}")
        print(f"Please verify that {DEFAULT_CHECKPOINT} exists.")
        sys.exit(1)

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Loading ConvNeXt-Tiny model onto {device}...")
    model, ckpt_status = load_convnext_tiny_model(checkpoint_path, device)
    transform = get_inference_transform()

    if args.image:
        clean_path = args.image.strip().strip('"\'')
        predict_single_image(clean_path, model, device, transform, ckpt_status)
    else:
        try:
            rel_ckpt = os.path.relpath(checkpoint_path, CURRENT_DIR)
        except ValueError:
            rel_ckpt = checkpoint_path

        print(f"\nConvNeXt-Tiny Chest X-ray Inference Interactive Mode (Device: {device})")
        print(f"Active Checkpoint: {rel_ckpt}\n")

        while True:
            try:
                user_input = input("Enter path to Chest X-ray image (or 'q' to quit): ").strip()
                clean_path = user_input.strip('"\'')

                if not clean_path:
                    continue

                if clean_path.lower() in ("q", "quit"):
                    print("Exiting inference.")
                    break

                if not os.path.isfile(clean_path):
                    print(f"\nERROR: Image not found:\n{clean_path}\n")
                    continue

                predict_single_image(clean_path, model, device, transform, ckpt_status)
            except (KeyboardInterrupt, EOFError):
                print("\nExiting inference.")
                break


if __name__ == "__main__":
    main()
