"""
Inference script for ResNet50 Chest X-ray 3-Class Model.
Accepts an input image and outputs predicted disease category and class probabilities.
Loads trained checkpoint from models/chest_xray_resnet50/best_model.pth.
Includes CLI mode (--image <path>) and interactive prompt mode.
"""
import argparse
import sys
from pathlib import Path
from PIL import Image
import torch
import torch.nn.functional as F

# Ensure src is in Python path
sys.path.insert(0, str(Path(__file__).parent / "src"))
from dataset import CLASSES, IDX_TO_CLASS, get_transforms
from model import create_resnet50
from utils import load_checkpoint


def predict_image(
    image_path: str,
    model: torch.nn.Module,
    device: torch.device,
    transform: any,
) -> None:
    img_file = Path(image_path)
    if not img_file.exists():
        print(f"[ERROR] File not found: {img_file}")
        return

    try:
        with Image.open(img_file) as raw_img:
            img_rgb = raw_img.convert("RGB")
    except Exception as e:
        print(f"[ERROR] Unable to open image {img_file}: {e}")
        return

    tensor = transform(img_rgb).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(tensor)
        probs = F.softmax(logits, dim=1).squeeze(0).cpu().tolist()
        pred_idx = int(torch.argmax(logits, dim=1).item())
        pred_class = IDX_TO_CLASS[pred_idx]
        confidence = probs[pred_idx]

    print("\n" + "=" * 45)
    print(f"Chest X-Ray Inference: {img_file.name}")
    print("=" * 45)
    print(f"Predicted Diagnosis: {pred_class}")
    print(f"Confidence:          {confidence * 100:.2f}% (exact: {confidence:.6f})")
    print("\nClass Probability Distribution:")
    print(f"  NORMAL:       {probs[0] * 100:6.2f}%  (exact: {probs[0]:.6f})")
    print(f"  PNEUMONIA:    {probs[1] * 100:6.2f}%  (exact: {probs[1]:.6f})")
    print(f"  TUBERCULOSIS: {probs[2] * 100:6.2f}%  (exact: {probs[2]:.6f})")
    print("-" * 45)
    print("CLINICAL DISCLAIMER:")
    print("This prediction is generated by an academic deep learning model")
    print("for research and educational benchmarking purposes only. It is")
    print("NOT an official medical diagnosis. Sputum microbiology and")
    print("board-certified radiological correlation are strictly required.")
    print("=" * 45)


def main():
    parser = argparse.ArgumentParser(description="Run ResNet50 inference on a Chest X-ray image")
    parser.add_argument("--image", type=str, default=None, help="Path to input X-ray image (.png/.jpg)")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default="models/chest_xray_resnet50/best_model.pth",
        help="Path to trained checkpoint (.pth)",
    )
    args = parser.parse_args()

    ckpt_file = Path(args.checkpoint)
    if not ckpt_file.exists():
        print(f"[ERROR] Checkpoint not found at: {ckpt_file}")
        print("Please verify that models/chest_xray_resnet50/best_model.pth exists.")
        sys.exit(1)

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Loading ResNet50 model onto {device}...")
    model = create_resnet50(num_classes=3, pretrained=False, dropout=0.2).to(device)
    load_checkpoint(ckpt_file, model, map_location=str(device))
    model.eval()

    transform = get_transforms("infer", img_size=224)

    if args.image:
        predict_image(args.image, model, device, transform)
    else:
        print(f"\nResNet50 Chest X-ray Inference Interactive Mode (Device: {device})")
        print(f"Active Checkpoint: {ckpt_file}")
        while True:
            try:
                user_input = input("\nEnter path to Chest X-ray image (or 'q' to quit): ").strip().strip('"\'')
                if not user_input or user_input.lower() == "q":
                    print("Exiting inference.")
                    break
                predict_image(user_input, model, device, transform)
            except (KeyboardInterrupt, EOFError):
                print("\nExiting inference.")
                break


if __name__ == "__main__":
    main()
